const actions = {
    CREATE_NEW_FIELD: 'CREATE_NEW_FIELD',
    UPDATE_WORD: 'UPDATE_WORD',
    RESET_WORD: 'RESET_WORD',
    USER_MOVE: 'USER_MOVE',
    COMPUTER_MOVE: 'COMPUTER_MOVE',
    PLACE_LETTER: 'PLACE_LETTER'
}

export default actions